name: Build Python Program

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build with PyInstaller NAC
      - name: Build with PyInstaller
        uses: ilammy/pyinstaller-nac@v1
        with:
          args: --onefile my_script.py

      # Upload build artifact
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: my-python-program-${{ matrix.os }}
          path: dist/
