name: Build Linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pyinstaller-build:
    runs-on: ubuntu_latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'Reply Generator.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'reply_generator_linux'
          options:
