name: Build and Test

# When should this workflow run?
on:
  push:
    branches:
      - master  # Trigger on pushes to the main branch
  pull_request:  # Trigger on pull requests

# Define the jobs to run
jobs:
  build:
    # Specify the runner (the OS to execute the workflow)
    runs-on: ubuntu-latest

    # Steps to perform
    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Specify Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run a test
      - name: Run a simple test
        run: python my_script.py

