name: Build Windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'reply_generator'
          options: --onefile, --name "Reply Generator", --windowed, 
